- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
#  - Bagel
  - Barratry
  - CorvaxBox
#  - Cluster
#  - Fland
#  - Kettle
#  - Marathon
#  - Meta
#  - Moose
#  - Omega
  - Origin
#  - Saltern
